package agentfeedback_test

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/santhosh-tekuri/jsonschema/v6"
	"go.yaml.in/yaml/v3"

	"github.com/agentfeedback/agentfeedback/v4/internal/harness"
)

var update = flag.Bool("update", false, "rewrite the generated integrations table in README.md")

type integration struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Kind    string `json:"kind"`
	Install string `json:"install"`
	Status  string `json:"status"`
	Date    string `json:"date"`
	Docs    string `json:"docs"`
}

func readJSON(t *testing.T, path string) any {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	v, err := jsonschema.UnmarshalJSON(f)
	if err != nil {
		t.Fatalf("%s: %v", path, err)
	}

	return v
}

// compile compiles the schema id, with every schema file in files added
// under its own $id, so nothing is fetched.
func compile(t *testing.T, id string, files ...string) *jsonschema.Schema {
	t.Helper()
	c := jsonschema.NewCompiler()
	for _, f := range files {
		doc := readJSON(t, f)
		sid, _ := doc.(map[string]any)["$id"].(string)
		if err := c.AddResource(sid, doc); err != nil {
			t.Fatal(err)
		}
	}
	s, err := c.Compile(id)
	if err != nil {
		t.Fatal(err)
	}

	return s
}

func loadIntegrations(t *testing.T) []integration {
	t.Helper()
	data, err := os.ReadFile("integrations.json")
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Integrations []integration `json:"integrations"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatal(err)
	}

	return doc.Integrations
}

func TestIntegrationsSchema(t *testing.T) {
	s := compile(t, "https://agentfeedback.dev/schemas/integrations.v1.json", "schemas/integrations.v1.json")
	if err := s.Validate(readJSON(t, "integrations.json")); err != nil {
		t.Fatalf("integrations.json: %v", err)
	}
	seen := map[string]bool{}
	for _, e := range loadIntegrations(t) {
		if seen[e.ID] {
			t.Errorf("id %s twice", e.ID)
		}
		seen[e.ID] = true
		if e.Docs != "" {
			if _, err := os.Stat(e.Docs); err != nil {
				t.Errorf("%s: docs %v", e.ID, err)
			}
		}
	}
}

// adapterInstall is the install command of an adapter entry: CLI mode when
// the harness supports it, else MCP mode.
func adapterInstall(name string) string {
	if ok, _ := harness.Supports(name, harness.ModeCLI); ok {
		return "`agentfeedback install " + name + "`"
	}

	return "`agentfeedback install " + name + " --mcp`"
}

func TestIntegrationsAdapters(t *testing.T) {
	var got []string
	entries := map[string]integration{}
	for _, e := range loadIntegrations(t) {
		if e.Kind == "adapter" {
			got = append(got, e.ID)
			entries[e.ID] = e
		}
	}
	var want []string
	for _, a := range harness.Adapters() {
		want = append(want, a.Name)
		e, ok := entries[a.Name]
		if !ok {
			continue
		}
		if e.Status != a.Verified.Level || e.Date != a.Verified.Date {
			t.Errorf("%s: status %s %s, the registry has %s %s", a.Name, e.Status, e.Date, a.Verified.Level, a.Verified.Date)
		}
		if w := adapterInstall(a.Name); e.Install != w {
			t.Errorf("%s: install %q, want %q", a.Name, e.Install, w)
		}
	}
	if !slices.Equal(got, want) {
		t.Errorf("adapter entries %v, the registry has %v in this order", got, want)
	}
}

// integrationsTable is the README table rendered from integrations.json.
func integrationsTable(entries []integration) string {
	esc := strings.NewReplacer("|", `\|`).Replace
	var b strings.Builder
	b.WriteString("| Integration | Kind | Install | Status |\n|---|---|---|---|\n")
	for _, e := range entries {
		name := esc(e.Name)
		if e.Docs != "" {
			name = "[" + name + "](" + e.Docs + ")"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s %s |\n", name, e.Kind, esc(e.Install), e.Status, e.Date)
	}

	return b.String()
}

func TestIntegrationsTable(t *testing.T) {
	const begin = "<!-- integrations-table:begin: generated by go test . -run TestIntegrationsTable -update -->\n"
	const end = "<!-- integrations-table:end -->"
	const path = "README.md"
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	doc := string(data)
	i, j := strings.Index(doc, begin), strings.Index(doc, end)
	if i < 0 || j < i {
		t.Fatalf("%s has no integrations-table block", path)
	}
	got, want := doc[i+len(begin):j], integrationsTable(loadIntegrations(t))
	if got == want {
		return
	}
	if !*update {
		t.Fatalf("the integrations table in %s is not integrations.json's; run go test . -run TestIntegrationsTable -update\ngot:\n%s\nwant:\n%s", path, got, want)
	}
	if err := os.WriteFile(path, []byte(doc[:i+len(begin)]+want+doc[j:]), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readYAML(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := yaml.Unmarshal(data, &m); err != nil {
		t.Fatalf("%s: %v", path, err)
	}

	return m
}

func match(t *testing.T, where, pattern string, v any) {
	t.Helper()
	s, ok := v.(string)
	if !ok || !regexp.MustCompile(pattern).MatchString(s) {
		t.Errorf("%s: %v does not match %s", where, v, pattern)
	}
}

func oneOf(t *testing.T, where string, v any, allowed ...string) {
	t.Helper()
	if s, ok := v.(string); !ok || !slices.Contains(allowed, s) {
		t.Errorf("%s: %v is not one of %v", where, v, allowed)
	}
}

// TestIntegrationsHubArtifacts checks the files submitted to the hubs
// against their catalogs' rules.
func TestIntegrationsHubArtifacts(t *testing.T) {
	t.Run("hermes-plugin-catalog", hermesCatalog)
	t.Run("hermes-optional-mcps", hermesMCP)
	t.Run("nanoclaw-template", nanoClaw)
}

// hermesCatalog applies the Hermes plugin catalog validator's rules.
func hermesCatalog(t *testing.T) {
	const path = "integrations/hermes/plugin-catalog/agentfeedback.yaml"
	m := readYAML(t, path)
	for _, k := range []string{"name", "repo", "sha", "description", "maintainer"} {
		if s, _ := m[k].(string); s == "" {
			t.Errorf("%s: %s missing", path, k)
		}
	}
	known := []string{"name", "repo", "sha", "subdir", "description", "maintainer", "tier", "category", "requires_hermes",
		"docs_url", "version", "image", "screenshots", "readme", "platforms", "title", "onboarding", "known_issues", "capabilities"}
	for k := range m {
		if !slices.Contains(known, k) {
			t.Errorf("%s: unknown key %s", path, k)
		}
	}
	match(t, path+" name", `^[a-z0-9_-]{1,64}$`, m["name"])
	match(t, path+" sha", `^[0-9a-f]{40}$`, m["sha"])
	match(t, path+" repo", `^https://`, m["repo"])
	match(t, path+" version", `^[A-Za-z0-9][A-Za-z0-9._+-]{0,31}$`, m["version"])
	oneOf(t, path+" tier", m["tier"], "official", "community")
	oneOf(t, path+" category", m["category"], "desktop", "memory", "platform", "web", "tools", "voice", "automation", "models", "general")
	if c, present := m["capabilities"]; present {
		caps, ok := c.(map[string]any)
		if !ok {
			t.Errorf("%s: capabilities is not a mapping", path)
		}
		for k, v := range caps {
			if !slices.Contains([]string{"provides_tools", "provides_hooks", "provides_middleware", "requires_env"}, k) {
				t.Errorf("%s: unknown capabilities key %s", path, k)
			}
			if _, ok := v.([]any); !ok {
				t.Errorf("%s: capabilities.%s is not a list", path, k)
			}
		}
	}
	sub, _ := m["subdir"].(string)
	if _, err := os.Stat(filepath.Join(sub, "plugin.json")); sub == "" || err != nil {
		t.Errorf("%s: subdir %q has no plugin.json", path, sub)
	}
}

// hermesMCP applies the Hermes optional-mcps catalog's rules.
func hermesMCP(t *testing.T) {
	const path = "integrations/hermes/optional-mcps/agentfeedback/manifest.yaml"
	m := readYAML(t, path)
	if m["manifest_version"] != 1 {
		t.Errorf("%s: manifest_version %v", path, m["manifest_version"])
	}
	match(t, path+" name", `^[A-Za-z0-9_-]+$`, m["name"])
	if s, _ := m["description"].(string); strings.TrimSpace(s) == "" {
		t.Errorf("%s: description empty", path)
	}
	tr, _ := m["transport"].(map[string]any)
	switch tr["type"] {
	case "stdio":
		if s, _ := tr["command"].(string); s == "" {
			t.Errorf("%s: stdio transport without command", path)
		}
	case "http":
		if s, _ := tr["url"].(string); s == "" {
			t.Errorf("%s: http transport without url", path)
		}
	default:
		t.Errorf("%s: transport type %v", path, tr["type"])
	}
	auth, _ := m["auth"].(map[string]any)
	oneOf(t, path+" auth.type", auth["type"], "api_key", "oauth", "none")
}

// nanoClaw applies the NanoClaw templates repository's checks;
// scripts/contract-check.py validates its two files against the Agent
// Plugins schemas.
func nanoClaw(t *testing.T) {
	const dir = "integrations/nanoclaw/agentfeedback"
	plugin, _ := readJSON(t, filepath.Join(dir, "plugin.json")).(map[string]any)
	match(t, dir+"/plugin.json name", `^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$`, plugin["name"])

	keyRe := regexp.MustCompile(`(?i)(TOKEN|SECRET|PASSW(OR)?D|API_?KEY|APIKEY|CREDENTIAL|PRIVATE_?KEY|AUTH)`)
	valRe := regexp.MustCompile(`^(sk-|ghp_|github_pat_|xox[a-z]-|AKIA|-----BEGIN )`)
	data, err := os.ReadFile(filepath.Join(dir, "mcp.json"))
	if err != nil {
		t.Fatal(err)
	}
	var mcp struct {
		Servers map[string]struct {
			Type    string            `json:"type"`
			URL     string            `json:"url"`
			Env     map[string]string `json:"env"`
			Headers map[string]string `json:"headers"`
		} `json:"mcpServers"`
	}
	if err := json.NewDecoder(bytes.NewReader(data)).Decode(&mcp); err != nil {
		t.Fatal(err)
	}
	if s, ok := mcp.Servers["agentfeedback"]; !ok || s.Type != "streamable-http" {
		t.Errorf("%s: mcp.json has no streamable-http server named agentfeedback", dir)
	}
	for name, s := range mcp.Servers {
		for _, kv := range []map[string]string{s.Env, s.Headers} {
			for k, v := range kv {
				if v != "placeholder" && (keyRe.MatchString(k) || valRe.MatchString(v)) {
					t.Errorf("%s: %s: %s holds a value that is not \"placeholder\"", dir, name, k)
				}
			}
		}
		if s.URL != "" {
			u, err := url.Parse(s.URL)
			if err != nil {
				t.Errorf("%s: %s: %v", dir, name, err)
			} else if slices.Contains([]string{"host.docker.internal", "gateway.docker.internal", "172.17.0.1"}, u.Hostname()) {
				t.Errorf("%s: %s: host %s is refused", dir, name, u.Hostname())
			}
		}
	}
	err = filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.Type()&os.ModeSymlink != 0 {
			t.Errorf("%s is a symlink", p)
		}

		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "README.md")); err != nil {
		t.Error(err)
	}
}
