package skillgen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/agentfeedback/agentfeedback/v4"
)

// FormDocs is the agentfeedback-docs skill: a directory, not a stdout form,
// so it is not in Forms and Docs renders it.
const FormDocs = "docs"

// File is one file of a rendered directory; Path is relative and uses
// forward slashes. Mode is the file's permission bits, 0 meaning 0644.
type File struct {
	Path string
	Data []byte
	Mode fs.FileMode
}

// DocsMeta is source/docs.json.
type DocsMeta struct {
	Name          string `json:"name"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	Version       string `json:"version"`
	License       string `json:"license"`
	Compatibility string `json:"compatibility"`
}

// Docs renders the agentfeedback-docs skill: SKILL.md, then every embedded
// reference file under references/ at its repository path, in path order.
func Docs() ([]File, error) {
	return renderDocs(sourceFS, agentfeedback.References)
}

func renderDocs(source, refs fs.FS) ([]File, error) {
	var m DocsMeta
	data, err := fs.ReadFile(source, "source/docs.json")
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&m); err != nil {
		return nil, fmt.Errorf("source/docs.json: %w", err)
	}
	if m.Name == "" || m.Title == "" || m.Description == "" || m.Version == "" {
		return nil, errors.New("source/docs.json: name, title, description and version are required")
	}

	var paths []string
	err = fs.WalkDir(refs, ".", func(p string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() {
			paths = append(paths, p)
		}

		return err
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	var b strings.Builder
	fmt.Fprintf(&b, "---\nname: %s\ndescription: %s\n", m.Name, yamlString(m.Description))
	if m.License != "" {
		fmt.Fprintf(&b, "license: %s\n", yamlString(m.License))
	}
	if m.Compatibility != "" {
		fmt.Fprintf(&b, "compatibility: %s\n", yamlString(m.Compatibility))
	}
	fmt.Fprintf(&b, "metadata:\n  author: AgentFeedback\n  version: %s\n---\n\n", yamlQuoted(m.Version))
	fmt.Fprintf(&b, "<!-- Generated by `agentfeedback skill render docs`; do not edit. -->\n\n")
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("The reference docs, JSON Schemas, OpenAPI document and install playbooks of AgentFeedback, " +
		"copied from the repository at this binary's version. Read the one file your task needs. " +
		"To file a friction report, use the agentfeedback skill.\n\n## References\n\n")

	files := []File{{Path: "SKILL.md"}}
	for _, p := range paths {
		data, err := fs.ReadFile(refs, p)
		if err != nil {
			return nil, err
		}
		line, err := describe(p, data)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", p, err)
		}
		if strings.TrimSpace(line) == "" || strings.ContainsAny(line, "\r\n") {
			return nil, fmt.Errorf("%s: no one-line description", p)
		}
		ref := "references/" + p
		fmt.Fprintf(&b, "- [%s](%s): %s\n", ref, ref, line)
		files = append(files, File{Path: ref, Data: data})
	}
	files[0].Data = []byte(b.String())

	return files, nil
}

// describe is the line SKILL.md lists a reference file with: a Markdown
// file's first level-1 heading, a schema's title (else its description), the
// OpenAPI document's info.title.
func describe(p string, data []byte) (string, error) {
	switch {
	case strings.HasSuffix(p, ".md"):
		var fence fenceState
		for _, l := range strings.Split(string(data), "\n") {
			if fence.inside() || fence.toggles(l) {
				fence.step(l)

				continue
			}
			if t, ok := strings.CutPrefix(l, "# "); ok {
				return strings.TrimSpace(t), nil
			}
		}

		return "", errors.New("no level-1 heading")
	case path.Ext(p) == ".json":
		var s struct{ Title, Description string }
		if err := json.Unmarshal(data, &s); err != nil {
			return "", err
		}
		if s.Title == "" {
			s.Title = s.Description
		}
		if s.Title == "" {
			return "", errors.New("no title or description")
		}

		return "JSON Schema: " + strings.TrimSpace(s.Title), nil
	case path.Ext(p) == ".yaml":
		var d struct {
			Info struct{ Title string } `yaml:"info"`
		}
		if err := yaml.Unmarshal(data, &d); err != nil {
			return "", err
		}
		if d.Info.Title == "" {
			return "", errors.New("no info.title")
		}

		return strings.TrimSpace(d.Info.Title) + " (OpenAPI document)", nil
	}

	return "", errors.New("no description rule for this file type")
}
