package harness

import (
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite the generated harness table in docs/operate.md")

func TestRegistry_Complete(t *testing.T) {
	e := testEnv(t)
	date := regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	seen := map[string]bool{}
	for _, a := range Adapters() {
		if a.Name == "" || seen[a.Name] {
			t.Fatalf("empty or repeated name %q", a.Name)
		}
		seen[a.Name] = true
		bad := func(what string) { t.Errorf("%s: %s", a.Name, what) }
		if len(a.Binaries) == 0 && len(a.ConfigDirs(e)) == 0 {
			bad("no binary and no config directory")
		}
		if len(a.SkillDirs(e)) == 0 && a.NoSkill == "" {
			bad("no skill directory and no reason")
		}
		if (a.Instructions.Global == nil || len(a.Instructions.Global(e)) == 0) && a.Instructions.NoGlobal == "" {
			bad("no global instruction file and no reason")
		}
		if len(a.Instructions.Project) == 0 {
			bad("no project instruction file")
		}
		switch {
		case a.Hook.Format == "":
			bad("no hook format")
		case a.Hook.Format == "none" && a.Hook.NoHook == "":
			bad("hook none without a reason")
		case a.Hook.Format != "none" && a.Hook.File == nil:
			bad("hook without a file")
		}
		for _, k := range []string{EventToolFailed, EventTurnEnd, EventSessionStart} {
			if a.Hook.Events[k] == "" {
				bad("event " + k + " missing")
			}
		}
		if a.MCP.URLShape == "" && a.MCP.NoMCP == "" {
			bad("no MCP entry and no reason")
		}
		if a.Sessions.Reader == "" || (a.Sessions.Reader == "none" && a.Sessions.NoReader == "") {
			bad("no session reader and no reason")
		}
		if !slices.Contains([]string{LevelDocumented, LevelFixtureTested, LevelLiveChecked}, a.Verified.Level) || !date.MatchString(a.Verified.Date) {
			bad("verification " + a.Verified.Level + " " + a.Verified.Date)
		}
		// Every mode is either wired or refused with a next step.
		for _, mode := range []string{ModeCLI, ModeMCP} {
			ok, reason := Supports(a.Name, mode)
			if !ok && reason == "" {
				bad(mode + " refused without a reason")
			}
		}
	}
	if !slices.Equal(Names(), names) || len(names) != len(seen) {
		t.Errorf("names %v", Names())
	}
}

func TestDocsHarnessTable(t *testing.T) {
	const begin = "<!-- harness-table:begin: generated by go test ./internal/harness -run TestDocsHarnessTable -update -->\n"
	const end = "<!-- harness-table:end -->"
	path := filepath.Join("..", "..", "docs", "operate.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	doc := string(data)
	i, j := strings.Index(doc, begin), strings.Index(doc, end)
	if i < 0 || j < i {
		t.Fatalf("%s has no harness-table block", path)
	}
	got, want := doc[i+len(begin):j], DocsTable()
	if got == want {
		return
	}
	if !*update {
		t.Fatalf("the harness table in %s is not the registry's; run go test ./internal/harness -run TestDocsHarnessTable -update\ngot:\n%s\nwant:\n%s", path, got, want)
	}
	if err := os.WriteFile(path, []byte(doc[:i+len(begin)]+want+doc[j:]), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestVSCodeUserDir(t *testing.T) {
	e := testEnv(t)
	orig := goos
	t.Cleanup(func() { goos = orig })
	goos = "linux"
	if got := e.vscodeUserDir(); got != filepath.Join(e.Home, ".config", "Code", "User") {
		t.Errorf("linux: %s", got)
	}
	goos = "darwin"
	if got := e.vscodeUserDir(); got != filepath.Join(e.Home, "Library", "Application Support", "Code", "User") {
		t.Errorf("darwin: %s", got)
	}
	goos = "windows"
	if got := e.vscodeUserDir(); got != filepath.Join(e.Home, "AppData", "Roaming", "Code", "User") {
		t.Errorf("windows without APPDATA: %s", got)
	}
	appdata := filepath.Join(e.Home, "roaming")
	e.Getenv = func(k string) string {
		if k == "APPDATA" {
			return appdata
		}

		return ""
	}
	if got := e.vscodeUserDir(); got != filepath.Join(appdata, "Code", "User") {
		t.Errorf("windows with APPDATA: %s", got)
	}
}

func TestInstall_DocsInEverySkillDir(t *testing.T) {
	e := testEnv(t)
	withDocs(t, map[string]string{"SKILL.md": "v1\n", "references/a.md": "# A\n"})
	if _, err := e.Run(docsRequest("antigravity")); err != nil {
		t.Fatal(err)
	}
	for _, d := range e.skillDirs("antigravity") {
		for _, f := range []string{filepath.Join("agentfeedback", "SKILL.md"), filepath.Join("agentfeedback-docs", "references", "a.md")} {
			if _, err := os.Stat(filepath.Join(d, f)); err != nil {
				t.Errorf("%v", err)
			}
		}
	}
	if _, err := e.Run(Request{Harnesses: []string{"antigravity"}, Uninstall: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(e.Home, ".gemini")); !os.IsNotExist(err) {
		t.Errorf("left behind: %v", err)
	}
}

func TestInstall_RefusedModes(t *testing.T) {
	e := testEnv(t)
	for _, tt := range []struct{ name, mode, problem string }{
		{"vscode", ModeCLI, "vscode has no skill directory of its own; VS Code reads the skill that the copilot or claude-code adapter installs"},
		{"gemini-cli", ModeMCP, "gemini-cli has no MCP entry in agentfeedback install"},
	} {
		req := cliRequest(tt.name)
		req.Options.Mode = tt.mode
		_, err := e.Run(req)
		r, ok := err.(*Refusal)
		if !ok || r.Problem != tt.problem {
			t.Errorf("%s/%s: %v", tt.name, tt.mode, err)
		}
	}
	if _, err := os.Stat(e.ManifestPath()); err == nil {
		t.Error("a manifest was written")
	}
}

// display is path in the form the docs table writes it.
func display(e Env, a Adapter, path string) string {
	type sub struct{ prefix, with string }
	subs := []sub{
		{e.claudeDir(), "<claude config>"}, {e.codexHome(), "<codex home>"}, {e.opencodeDir(), "<opencode>"},
		{e.vscodeUserDir(), "<Code/User>"}, {e.Home, "~"},
	}
	if a.Name == "amp" {
		subs = append(subs, sub{e.xdgConfig(), "<xdg>"})
	}
	slices.SortStableFunc(subs, func(x, y sub) int { return len(y.prefix) - len(x.prefix) })
	for _, s := range subs {
		if rest, ok := strings.CutPrefix(path, s.prefix); ok && (rest == "" || strings.HasPrefix(rest, "/")) {
			return s.with + rest
		}
	}

	return path
}

func TestRegistry_AgreesWithWiring(t *testing.T) {
	orig := goos
	t.Cleanup(func() { goos = orig })
	goos = "linux"
	e := testEnv(t)
	withDocs(t, map[string]string{"SKILL.md": "v1\n"})
	for _, a := range Adapters() {
		config, owned := registry[slices.IndexFunc(registry, func(r Adapter) bool { return r.Name == a.Name })].files(e)
		known := append(slices.Clone(config), owned...)
		hookFile := ""
		if a.Hook.File != nil {
			hookFile = a.Hook.File(e)
		}
		if (hookFile != "") != (a.Hook.Format != "none") {
			t.Errorf("%s: hook file %q with format %s", a.Name, hookFile, a.Hook.Format)
		}
		mcpFile := ""
		if a.MCP.File != nil {
			mcpFile = a.MCP.File(e)
		}
		for _, mode := range []string{ModeCLI, ModeMCP} {
			if ok, _ := Supports(a.Name, mode); !ok {
				continue
			}
			p := newPlan(e, newManifest())
			d, err := p.desired(a.Name, Options{Mode: mode, Reminder: true, Docs: true, Server: "https://x.test", Binary: "/bin/af"})
			if err != nil {
				t.Fatalf("%s/%s: %v", a.Name, mode, err)
			}
			sawHook := false
			for _, it := range d.items {
				if it.Kind == KindClaudeMCP {
					continue
				}
				bad := func(why string) { t.Errorf("%s/%s: %s %s: %s", a.Name, mode, it.Role, it.File, why) }
				switch it.Role {
				case RoleSkill, RoleDocs:
					if !slices.ContainsFunc(a.SkillDirs(e), func(d string) bool { return strings.HasPrefix(it.File, d+"/") }) {
						bad("not under a skill directory")
					}

					continue
				case RoleHook, RoleReminder:
					sawHook = true
					if it.File != hookFile {
						bad("not Hook.File " + hookFile)
					}
				case RoleMCP:
					if it.File != mcpFile && !slices.Contains(config, it.File) {
						bad("not MCP.File " + mcpFile)
					}
				}
				if !slices.Contains(known, it.File) {
					bad("not in files()")
				}
			}
			if mode == ModeCLI && sawHook != (a.Hook.Format != "none") {
				t.Errorf("%s: hook items %v with format %s", a.Name, sawHook, a.Hook.Format)
			}
		}
		// The docs row names the declared paths.
		r := registry[slices.IndexFunc(registry, func(r Adapter) bool { return r.Name == a.Name })].row
		for _, d := range a.SkillDirs(e) {
			if want := display(e, a, filepath.Join(d, "agentfeedback", "SKILL.md")); !strings.Contains(r.skill, want) {
				t.Errorf("%s: skill cell %q lacks %s", a.Name, r.skill, want)
			}
		}
		if a.Hook.Format != "none" {
			if want := display(e, a, hookFile); !strings.Contains(r.hook, want) {
				t.Errorf("%s: hook cell %q lacks %s", a.Name, r.hook, want)
			}
		}
		if mcpFile != "" && a.Name != "claude-code" {
			want := display(e, a, mcpFile)
			if a.Name == "opencode" || a.Name == "amp" {
				want = filepath.Base(mcpFile)
			}
			if !strings.Contains(r.mcp, want) {
				t.Errorf("%s: mcp cell %q lacks %s", a.Name, r.mcp, want)
			}
		}
	}
	var rows []string
	for _, line := range strings.Split(strings.TrimSpace(DocsTable()), "\n")[2:] {
		name, _, _ := strings.Cut(strings.TrimPrefix(line, "| `"), "`")
		rows = append(rows, name)
	}
	if !slices.Equal(rows, Names()) {
		t.Errorf("table rows %v", rows)
	}
}
